package com.addon.user.myapplication.db;
/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

import android.database.sqlite.SQLiteDatabase;

public class ErgExp {

    public void insert(SQLiteDatabase paramSQLiteDatabase)
    {
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (2,200,200 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (3,250,450 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (4,300,750 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (5,350,1100 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (6,710,1810 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (7,1017,2827 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (8,1303,4130 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (9,1575,5705 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (10,1841,7546 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (11,3509,11055 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (12,3962,15017 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (13,4438,19455 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (14,4948,24403 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (15,5504,29907 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (16,9477,39384 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (17,17427,56811 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (18,21606,78417 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (19,24048,102465 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (20,26786,129251 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (21,29853,159104 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (22,36282,195386 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (23,39105,234491 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (24,43357,277848 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (25,46069,323917 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (26,51275,375192 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (27,57008,432200 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (28,63301,495501 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (29,68186,563687 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (30,71697,635384 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (31,74867,710251 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (32,84728,794979 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (33,94314,889293 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (34,104658,993951 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (35,122792,1116743 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (36,137749,1254492 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (37,163000,1417492 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (38,195500,1612992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (39,227000,1839992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (40,275000,2114992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (41,325000,2439992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (42,390000,2829992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (43,470000,3299992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (44,560000,3859992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (45,650000,4509992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (46,740000,5249992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (47,830000,6079992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (48,940000,7019992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (49,1040000,8059992 );");
        paramSQLiteDatabase.execSQL("INSERT INTO ERGEXP ( ergLevel, exp, totalExp ) VALUES (50,1150000,9209992 );");
    }
}
