package com.addon.user.myapplication.db;
/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

import android.database.sqlite.SQLiteDatabase;

public class Local {

    public void insert(SQLiteDatabase paramSQLiteDatabase)
    {
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'instrumentRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'songRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BFRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'VVRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BVRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'MCRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'SPRank', '0');");

        // 타이틀 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'firstTitleSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'secondTitleSpinner', '0');");

        // 무기 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponSelectedSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponInchant2Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponMusicPlusSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponNMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponGMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'weaponBMESpinner', '0');");

        // 왼쪽 악세 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryInchant2Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryNMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryGMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryBMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryVVMSSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryVVASSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'leftAccessoryBVGSSpinner', '0');");

        // 오른쪽 악세 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryInchant2Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryNMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryGMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryBMESpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryVVMSSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryVVASSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'rightAccessoryBVGSSpinner', '0');");

        // 머리 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'headInchant2Spinner', '0');");

        // 옷 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'clothInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'clothInchant2Spinner', '0');");

        // 장갑 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'handClothInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'handClothBVGSSpinner', '0');");

        // 신발 SPINNER SETTING
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'shoesInchant1Spinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'shoesVVMSSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'shoesVVASSpinner', '0');");

        // 추가 요소
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherGrandMasterSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherTrumpetSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherPotionSpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherPartySpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherEcostoneKeySpinner', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'otherEcostoneValueSpinner', '0');");
    }
}
