package com.addon.user.myapplication.db;
/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

import android.database.sqlite.SQLiteDatabase;

public class Local {

    public void insert(SQLiteDatabase paramSQLiteDatabase)
    {
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'instrumentRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'songRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BFRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'VVRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BVRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'MCRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'SPRank', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'musicPlusCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BFCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'VVCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BYCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'MCCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'SPCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'VVMSCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'VVASCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BVGSCountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'NMECountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'GMECountEditText', '0');");
        paramSQLiteDatabase.execSQL("INSERT INTO LOCALDATATABLE ( useLayout, keyName, keyContent ) VALUES ('MUSIC', 'BMECountEditText', '0');");
    }
}
