/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.db;

import android.database.sqlite.SQLiteDatabase;

public class TradeItem {
    
    public void insert(SQLiteDatabase db) {
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('티르코네일','베이비포션', 1, 80)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('티르코네일','다이어트포션', 1, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('티르코네일','코골이방지포션', 2, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('티르코네일','산삼포션', 3, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('티르코네일','러블리포션', 3, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('던바튼','거미줄장갑', 5, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('던바튼','양털부츠', 8, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('던바튼','오거도살자가면', 4, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('던바튼','인큐버스정장', 25, 5)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('던바튼','서큐버스수영복', 6, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('반호르','반호르산석탄', 8, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('반호르','대리석', 20, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('반호르','황수정', 25, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('반호르','하이랜더광석', 30, 8)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('반호르','납', 30, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('이멘마하','베리그래놀라', 3, 40)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('이멘마하','버터맥주', 4, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('이멘마하','훈제야생동물구이', 3, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('이멘마하','트뤼플파스타', 5, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('이멘마하','통곰바베큐', 40, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('탈틴','열기의결정', 2, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('탈틴','오르골보존석', 3, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('탈틴','팔라라결정', 2, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('탈틴','원형방호벽결정', 4, 100)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('탈틴','연금결정', 5, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('타라','미니화장대', 20, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('타라','티테이블', 25, 5)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('타라','흔들의자', 25, 5)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('타라','어린이2층침대', 75, 3)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('타라','대형와인랙', 300, 1)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('카브항구','카브산김', 2, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('카브항구','카브산굴', 3, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('카브항구','상어지느러미', 4, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('카브항구','젤리해파리', 6, 30)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('카브항구','네이드비늘', 2, 50)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('벨바스트','쇠채찍', 8, 15)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('벨바스트','다크소드', 12, 10)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('벨바스트','금고', 220, 1)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('벨바스트','스켈레톤오거갑옷', 180, 1)");
        db.execSQL("INSERT INTO TRADEITEM ( town, item, weight, slotValue ) VALUES ('벨바스트','모조모르간트헬멧', 40, 10)");
    }
}
