/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.view;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.ArrayList;
import android.widget.TextView;
import android.view.View;
import android.view.ViewGroup;
import android.view.LayoutInflater;

import com.addon.user.myapplication.R;

public class NoticeAdapter extends BaseAdapter {
    Context context;
    ArrayList<NoticeItem> noticeArrayList;
    TextView noticeContentView;
    TextView noticeDateView;
    TextView noticeTitleView;
    
    public NoticeAdapter(Context context, ArrayList<NoticeItem> noticeArrayList) {
        this.context = context;
        this.noticeArrayList = noticeArrayList;
    }
    
    public int getCount() {
        return noticeArrayList.size();
    }
    
    public Object getItem(int position) {
        return noticeArrayList.get(position);
    }

    public long getItemId(int position) {
        return position;
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        if(convertView == null) {
            convertView = LayoutInflater.from(context).inflate(R.layout.notice_item, null);
            noticeTitleView = (TextView)convertView.findViewById(R.id.noticeTitleView);
            noticeTitleView.setText(noticeArrayList.get(position).getTitle());
            noticeDateView = (TextView)convertView.findViewById(R.id.noticeDateView);
            noticeDateView.setText(noticeArrayList.get(position).getDate());
        }
        return convertView;
    }
}
