/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.view;

import java.io.Serializable;

public class NoticeItem implements Serializable {
    private String content;
    private String date;
    private String title;
    
    public NoticeItem(String title, String date, String content) {
        this.title = title;
        this.date = date;
        this.content = content;
    }
    
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getDate() {
        return date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    public String getContent() {
        return content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
}
