/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.view;


public class RankItem {
    private String finishValue;
    private int rank;
    private String townName;
    
    public RankItem() {
        finishValue = "";
        rank = 0;
    }
    
    public String getTownName() {
        return townName;
    }
    
    public void setTownName(String townName) {
        this.townName = townName;
    }
    
    public String getFinishValue() {
        return finishValue;
    }
    
    public void setFinishValue(String finishValue) {
        this.finishValue = finishValue;
    }
    
    public int getRank() {
        return rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }
}
