/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.view;

import android.widget.BaseAdapter;
import android.content.Context;
import java.util.ArrayList;
import android.widget.TextView;
import android.view.View;
import android.view.ViewGroup;
import android.view.LayoutInflater;

import com.addon.user.myapplication.R;

public class TitleAdapter extends BaseAdapter {
    Context context;
    ArrayList<TitleItem> titleArrayList;
    TextView titleIdView;
    TextView titleKindView;
    TextView titleNameView;
    TextView titleSecondStringView;
    
    public TitleAdapter(Context context, ArrayList<TitleItem> titleArrayList) {
        this.context = context;
        this.titleArrayList = titleArrayList;
    }
    
    public int getCount() {
        return titleArrayList.size();
    }
    
    public Object getItem(int position) {
        return titleArrayList.get(position);
    }

    public long getItemId(int position) {
        return position;
    }
    
    public View getView(int position, View convertView, ViewGroup parent) {
        if(convertView == null) {
            convertView = LayoutInflater.from(context).inflate(R.layout.title_item, null);
            titleIdView = (TextView)convertView.findViewById(R.id.titleIdView);
            titleIdView.setText(String.valueOf(titleArrayList.get(position).getTitleId()));

            titleNameView = (TextView)convertView.findViewById(R.id.titleNameView);
            titleNameView.setText(titleArrayList.get(position).getTitleName());

            titleKindView = (TextView)convertView.findViewById(R.id.titleKindView);
            titleKindView.setText(titleArrayList.get(position).getTitleKind());

            titleSecondStringView = (TextView)convertView.findViewById(R.id.titleSecondStringView);
            titleSecondStringView.setText(titleArrayList.get(position).getTitleSecondString());
        }
        return convertView;
    }
}
