/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.view;


public class TitleItem {
    private String afterComment;
    private String beforeComment;
    private String howGet;
    private String titleCategory;
    private int titleId;
    private String titleKind;
    private String titleName;
    private String titleNumber;
    private String titleSecondString;
    
    public int getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }
    
    public String getTitleNumber() {
        return this.titleNumber;
    }
    
    public void setTitleNumber(String titleNumber) {
        this.titleNumber = titleNumber;
    }
    
    public String getTitleName() {
        return this.titleName;
    }
    
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
    
    public String getTitleKind() {
        return this.titleKind;
    }
    
    public void setTitleKind(String titleKind) {
        this.titleKind = titleKind;
    }
    
    public String getTitleCategory() {
        return this.titleCategory;
    }
    
    public void setTitleCategory(String titleCategory) {
        this.titleCategory = titleCategory;
    }
    
    public String getBeforeComment() {
        return this.beforeComment;
    }
    
    public void setBeforeComment(String beforeComment) {
        this.beforeComment = beforeComment;
    }
    
    public String getAfterComment() {
        return this.afterComment;
    }
    
    public void setAfterComment(String afterComment) {
        this.afterComment = afterComment;
    }
    
    public String getHowGet() {
        return this.howGet;
    }
    
    public void setHowGet(String howGet) {
        this.howGet = howGet;
    }
    
    public String getTitleSecondString() {
        return this.titleSecondString;
    }
    
    public void setTitleSecondString(String titleSecondString) {
        this.titleSecondString = titleSecondString;
    }
}
