/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import android.widget.LinearLayout;
import android.content.Context;
import com.addon.user.myapplication.GlobalVariablesActivity;
import android.view.LayoutInflater;
import android.util.AttributeSet;
import android.view.View;
import android.view.ViewGroup;
import android.database.sqlite.SQLiteDatabase;

public abstract class BaseLinearLayout extends LinearLayout {
    public final Context context;
    public final GlobalVariablesActivity global;
    public final LayoutInflater inflater;
    
    public abstract void initialization(Object[] p1);
    
    
    public abstract void setData(SQLiteDatabase p1, Object[] p2);
    
    
    public abstract void setData(Object[] p1);
    
    
    public BaseLinearLayout(Context context, AttributeSet attr) {
        super(context, attr);
        this.context = context;
        this.inflater = (LayoutInflater)context.getSystemService("layout_inflater");
        this.global = (GlobalVariablesActivity)context.getApplicationContext();
    }
    
    public BaseLinearLayout(Context context) {
        super(context);
        this.context = context;
        this.inflater = (LayoutInflater)context.getSystemService("layout_inflater");
        this.global = (GlobalVariablesActivity)context.getApplicationContext();
    }
    
    public View getView(int id) {
        return inflater.inflate(id, null);
    }
}
