/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.graphics.Typeface;
import android.util.TypedValue;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.addon.user.myapplication.MainActivity;
import com.addon.user.myapplication.R;

public class HistoryLayout extends BaseLinearLayout {
    public RelativeLayout layout;
    public MainActivity mainActivity;

    // VIEW
    private LinearLayout homeContentLayout;

    public HistoryLayout(Context context) {
        super(context);
    }

    public void initialization(Object[] obj) {

        layout = (RelativeLayout)getView(R.layout.history_layout);
        addView(layout);

        homeContentLayout = (LinearLayout) findViewById(R.id.homeContentLayout);

        setContentLayout("T", "＊ 2018-09-17");
        setContentLayout("C", "     ◎ 일부 안드로이드 버젼에서 비정상 종료 오류 수정");

        setContentLayout("T", "＊ 2018-09-15");
        setContentLayout("C", "     ◎ 메인 화면 요일 및 효과 추가");
        setContentLayout("C", "     ◎ 에르그 효과 디자인 변경");

        setContentLayout("T", "＊ 2018-09-14");
        setContentLayout("C", "     ◎ 광고 오류 수정");
        setContentLayout("C", "     ◎ 메인 화면 변경");

        setContentLayout("T", "＊ 2018-09-12");
        setContentLayout("C", "     ◎ 연주 도우미 베타 서비스 추가");

        setContentLayout("T", "＊ 2018-09-01");
        setContentLayout("C", "     ◎ 업데이트 시, 비정상 종료 오류 수정");

        setContentLayout("T", "＊ 2018-08-31");
        setContentLayout("C", "     ◎ 폰트 변경");
        setContentLayout("C", "     ◎ 에르그 조회 서비스 추가");

        setContentLayout("T", "＊ 2018-08-01");
        setContentLayout("C", "     ◎ 소스 복원");

        setContentLayout("T", "＊ 2017-10-15");
        setContentLayout("C", "     ◎ 포맷하다가 소스 날림");

        setContentLayout("T", "＊ 2017-09-26");
        setContentLayout("C", "     ◎ 어플리케이션 오픈");
        setContentLayout("C", "     ◎ 교역도우미 서비스 추가");
    }

    private void setContentLayout(String gubun, String content){
        TextView contentTextView = new TextView(context);
        ViewGroup.LayoutParams contentTextViewLayoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        if(gubun.equals("T")){
            // 제목
            contentTextView.setLayoutParams(contentTextViewLayoutParams);
            contentTextView.setTextColor(Color.parseColor("#9F9F9F"));
            contentTextView.setTypeface(contentTextView.getTypeface(), Typeface.BOLD_ITALIC);
            contentTextView.setTextSize(TypedValue.COMPLEX_UNIT_DIP, 20);
            contentTextView.setPadding(0,30,0,0);
        }else if(gubun.equals("C")){
            // 내용
            contentTextView.setLayoutParams(contentTextViewLayoutParams);
            contentTextView.setTextColor(Color.parseColor("#9F9F9F"));
            contentTextView.setTextSize(TypedValue.COMPLEX_UNIT_DIP, 16);
            contentTextView.setPadding(0,15,0,0);
        }
        contentTextView.setText(content);
        homeContentLayout.addView(contentTextView);
    }
    
    public void setData(SQLiteDatabase db, Object[] obj) {
    }
    
    public void setData(Object[] obj) {
    }
}
