/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.graphics.Typeface;
import android.util.TypedValue;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.addon.user.myapplication.MainActivity;
import com.addon.user.myapplication.R;

import org.w3c.dom.Text;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

public class HomeLayout extends BaseLinearLayout {
    public RelativeLayout layout;
    public MainActivity mainActivity;

    // VIEW
    private TextView errinTimeTextView;
    private TextView mainMenu1;
    private TextView mainMenu2;
    private TextView mainMenu3;

    public HomeLayout(Context context) {
        super(context);
    }

    public void initialization(Object[] obj) {

        layout = (RelativeLayout)getView(R.layout.home_layout);
        addView(layout);

        // VIEW SETTING
        setView();

        // EVENT SETTING
        setEvent();

        // 1초 마다 실행하는 타이머 세팅
        Timer m_timer = new Timer(true);
        TimerTask m_task = new TimerTask() {
            @Override
            public void run() {
                errinTimeUpdate();
            }
        };
        m_timer.schedule(m_task, 0, 1000);
    }

    /**
     * 뷰 세팅
     */
    private void setView(){
        errinTimeTextView = findViewById(R.id.errinTime);
        mainMenu1 = findViewById(R.id.main_menu_1);
        mainMenu2 = findViewById(R.id.main_menu_2);
        mainMenu3 = findViewById(R.id.main_menu_3);
    }

    /**
     * 이벤트 세팅
     */
    private void setEvent(){
        mainMenu1.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                mainActivity.navigationView.getMenu().getItem(1).setChecked(true);
                mainActivity.moveMenuForLayout("trade");
            }
        });

        mainMenu2.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                mainActivity.navigationView.getMenu().getItem(2).setChecked(true);
                mainActivity.moveMenuForLayout("erg");
            }
        });

        mainMenu3.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                mainActivity.navigationView.getMenu().getItem(3).setChecked(true);
                mainActivity.moveMenuForLayout("music");
            }
        });
    }
    
    public void setData(SQLiteDatabase db, Object[] obj) {
    }
    
    public void setData(Object[] obj) {
    }

    /**
     * 에린 시간 업데이트
     */
    private void errinTimeUpdate(){
        // 현재 시간 가져오기
        long now = System.currentTimeMillis();
        Date currentTime = new Date(now);

        int year = currentTime.getYear();
        int month = currentTime.getMonth();
        int day = currentTime.getDay();
        int hrs = currentTime.getHours();
        int min = currentTime.getMinutes();
        int sec = currentTime.getSeconds();

        // 현재 시간 글자 세팅
        String hrsStr = "0";
        String minStr = "0";
        String secStr = "0";

        // 현재 시간이 2글자가 아니면 다시 설정
        if (hrs < 10) hrsStr = "0" + String.valueOf(hrs);
        if (min < 10) minStr = "0" + String.valueOf(min);
        if (sec < 10) secStr = "0" + String.valueOf(sec);

        // 자정 시간 가져오기
        Date midnightDate = new Date(year, month, day, 0, 0, 0);
        long midnightTime = midnightDate.getTime();

        // 에린시각 표시갱신 (에린의 하루는 현실시각으로 36분, 2160초)
        int erinnTime = Math.round((now - midnightTime) / 1000) % 2160;
        errinTimeTextView.setText(sec2minsec(Math.round(erinnTime * 2 / 3)));
    }

    /**
     * 에린 시간 계산
     * @param secs
     * @return
     */
    private String sec2minsec(int secs){

        double hrsDouble = Math.floor(secs / 60);
        double minDouble = secs % 60;

        String hrsStr = String.valueOf(hrsDouble).replace(".0","");
        String minStr = String.valueOf(minDouble).replace(".0","");

        if (hrsDouble < 10) hrsStr = "0" + hrsStr;
        if (minDouble < 10) minStr = "0" + minStr;

        return hrsStr + ":" + minStr;
    }
}
