/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.LinearLayout;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Spinner;

import com.addon.user.myapplication.MainActivity;
import com.addon.user.myapplication.R;
import com.addon.user.myapplication.view.NoticeAdapter;
import com.addon.user.myapplication.view.NoticeItem;

import java.util.ArrayList;

public class MusicLayout extends BaseLinearLayout {
    public LinearLayout layout;
    public MainActivity mainActivity;

    // VIEW
    private Spinner instrumentRankSpinner;
    private Spinner songRankSpinner;
    private Spinner DFRankSpinner;
    private Spinner VVRankSpinner;
    private Spinner BVRankSpinner;
    private Spinner MCRankSpinner;
    private Spinner SPRankSpinner;

    // SPINNER DATA ARRAY
    private ArrayAdapter<CharSequence> IRSDataArray;
    private ArrayAdapter<CharSequence> SONGDataArray;
    private ArrayAdapter<CharSequence> DFRDataArray;
    private ArrayAdapter<CharSequence> VVRDataArray;
    private ArrayAdapter<CharSequence> BVRDataArray;
    private ArrayAdapter<CharSequence> MCRDataArray;
    private ArrayAdapter<CharSequence> SPRDataArray;

    public MusicLayout(Context context) {
        super(context);
    }

    public void initialization(Object[] obj) {
        layout = (LinearLayout)getView(R.layout.music_layout);
        addView(layout);

        // SPINNER SETTING
        instrumentRankSpinner = layout.findViewById(R.id.instrumentRankSpinner);
        songRankSpinner = layout.findViewById(R.id.songRankSpinner);
        DFRankSpinner = layout.findViewById(R.id.DFRankSpinner);
        VVRankSpinner = layout.findViewById(R.id.VVRankSpinner);
        BVRankSpinner = layout.findViewById(R.id.BVRankSpinner);
        MCRankSpinner = layout.findViewById(R.id.MCRankSpinner);
        SPRankSpinner = layout.findViewById(R.id.SPRankSpinner);

        this.setSpinnerData();
    }

    public void setSpinnerData(){
        // 악기 연주 랭크
        // instrumentRankSpinner.setPrompt("출발 마을을 선택하시오.");
        IRSDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        IRSDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        instrumentRankSpinner.setAdapter(IRSDataArray);

        // 노래 랭크
        SONGDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        SONGDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        songRankSpinner.setAdapter(SONGDataArray);

        // 전장의 서곡 랭크
        DFRDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        DFRDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        DFRankSpinner.setAdapter(DFRDataArray);

        // 비바체 랭크
        VVRDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        VVRDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        VVRankSpinner.setAdapter(VVRDataArray);

        // 풍년가 랭크
        BVRDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        BVRDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        BVRankSpinner.setAdapter(BVRDataArray);

        // 행진곡 랭크
        MCRDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        MCRDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        MCRankSpinner.setAdapter(MCRDataArray);

        // 인내의 노래 랭크
        SPRDataArray = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        SPRDataArray.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        SPRankSpinner.setAdapter(SPRDataArray);
    }
    
    public void setData(SQLiteDatabase db, Object[] obj) {
    }
    
    public void setData(Object[] obj) {
    }
}
