/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import java.util.ArrayList;

import com.addon.user.myapplication.R;
import com.addon.user.myapplication.view.NoticeItem;
import android.widget.LinearLayout;
import android.widget.ListView;
import com.addon.user.myapplication.MainActivity;
import com.addon.user.myapplication.view.NoticeAdapter;
import android.content.Context;
import android.widget.ListAdapter;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.database.sqlite.SQLiteDatabase;

public class NoticeLayout extends BaseLinearLayout {
    public ArrayList<NoticeItem> arrayList;
    public LinearLayout layout;
    public ListView listView;
    public MainActivity mainActivity;
    public NoticeAdapter noticeAdapter;
    
    public NoticeLayout(Context context) {
        super(context);
    }
    
    public void initialization(Object[] obj) {

        layout = (LinearLayout)getView(R.layout.notice_layout);
        addView(layout);
        listView = (ListView)findViewById(R.id.noticeListView);
        arrayList = new ArrayList();
        arrayList.add(new NoticeItem("제목1", "2017-09-26", "내용1"));
        arrayList.add(new NoticeItem("제목2", "2017-09-26", "내용2"));
        noticeAdapter = new NoticeAdapter(getContext(), arrayList);
        listView.setAdapter(noticeAdapter);
        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            
            public void onItemClick(AdapterView parent, View view, int position, long id) {
                MainActivity.thisActivity.noticeDetail(position, view, arrayList);
            }
        });
        ViewGroup.LayoutParams params = listView.getLayoutParams();
        params.height = (MainActivity.thisActivity.deviceHeight - (MainActivity.thisActivity.deviceHeight / 7));
        listView.setLayoutParams(params);
        listView.requestLayout();
    }
    
    public static void setListViewHeightBasedOnChildren(ListView listView) {
        ListAdapter listAdapter = listView.getAdapter();
        if(listAdapter == null) {
            return;
        }
        int totalHeight = 0;
        int desiredWidth = View.MeasureSpec.makeMeasureSpec(listView.getWidth(), 0x80000000);
        for(int i = 0; i < (listAdapter.getCount() - 1); i++) {
            View listItem = listAdapter.getView(i, null, listView);
            listItem.measure(desiredWidth, 0);
            totalHeight += listItem.getMeasuredHeight();
        }
        ViewGroup.LayoutParams params = listView.getLayoutParams();
        params.height = (totalHeight - (listView.getDividerHeight() * (listAdapter.getCount() - 1)));
        listView.setLayoutParams(params);
        listView.requestLayout();
    }
    
    public void setData(SQLiteDatabase db, Object[] obj) {
    }
    
    public void setData(Object[] obj) {
    }
}
