/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication.layout;

import android.view.KeyEvent;
import android.widget.ArrayAdapter;
import android.widget.LinearLayout;
import java.util.HashMap;

import com.addon.user.myapplication.R;
import com.addon.user.myapplication.view.RankItem;
import android.database.sqlite.SQLiteDatabase;
import android.database.Cursor;
import android.content.Context;
import android.view.View;
import android.widget.HorizontalScrollView;
import android.widget.TextView;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.AdapterView;
import android.widget.Button;

public class TradeLayout extends BaseLinearLayout {
    ArrayAdapter<CharSequence> adspin;
    ArrayAdapter<CharSequence> adspinGrandMaster;
    ArrayAdapter<CharSequence> adspinItem;
    ArrayAdapter<CharSequence> adspinLOG;
    ArrayAdapter<CharSequence> adspinMastery;
    public LinearLayout layout;
    SQLiteDatabase tradeDb;
    Cursor tradeMeansOfCursor;
    
    public TradeLayout(Context context) {
        super(context);
    }

    CharSequence adspinStr = "";
    CharSequence adspinItemStr = "";
    int adspinLOGInt = 0;
    double LOGValue = 0.0;
    CharSequence adspinGrandMasterStr = "";
    int adspinMasteryInt = 0;
    double masteryValue = 0.0;
    int instanceItemCount = 0;
    int instanceMaxCount = 0;
    int instanceTradeMaxCount = 0;
    HashMap<String, RankItem> rankArray = new HashMap();
    String time1 = "0";
    String time2 = "0";
    String time3 = "0";
    String time4 = "0";
    String time5 = "0";
    String time6 = "0";
    String time7 = "0";
    String time8 = "0";
    boolean isView1 = true;
    boolean isView2 = true;
    boolean isView3 = true;
    boolean isView4 = true;
    boolean isView5 = true;
    boolean isView6 = true;
    boolean isView7 = true;
    boolean isView8 = true;
    
    public void initialization(Object[] obj) {
        layout = (LinearLayout)getView(R.layout.trade_layout);
        addView(layout);
        rankArray.put("티르코네일", new RankItem());
        rankArray.put("던바튼", new RankItem());
        rankArray.put("반호르", new RankItem());
        rankArray.put("이멘마하", new RankItem());
        rankArray.put("탈틴", new RankItem());
        rankArray.put("타라", new RankItem());
        rankArray.put("카브항구", new RankItem());
        rankArray.put("벨바스트", new RankItem());
    }
    
    public void setData(SQLiteDatabase db, Object[] obj) {
        tradeDb = db;
    }
    
    public void setData(Object[] obj) {
    }
    
    public void tradeLayoutAdd() {
        Spinner spinner = (Spinner)findViewById(R.id.townSpinner);
        spinner.setPrompt("출발 마을을 선택하시오.");
        adspin = ArrayAdapter.createFromResource(context, R.array.townSelected, R.layout.support_simple_spinner_dropdown_item);
        adspin.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        spinner.setAdapter(adspin);
        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            public void onItemSelected(AdapterView<?> paramAdapterView, View paramView, int paramInt, long paramLong)
            {
                adspinStr = adspin.getItem(paramInt);
                AfterTradeTown();
            }

            public void onNothingSelected(AdapterView<?> paramAdapterView) {}
        });

        Spinner LOGspinner = (Spinner)findViewById(R.id.LOGSpinner);
        adspinLOG = ArrayAdapter.createFromResource(context, R.array.LOGSelected, R.layout.support_simple_spinner_dropdown_item);
        adspinLOG.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        LOGspinner.setAdapter(adspinLOG);
        LOGspinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            public void onItemSelected(AdapterView<?> paramAdapterView, View paramView, int paramInt, long paramLong)
            {
                String str = (String) adspinLOG.getItem(paramInt);
                if (str.equals("사용안함(0%)")) {
                    adspinLOGInt = 0;
                }else if (str.equals("오거 (30%)")) {
                    adspinLOGInt = 30;
                }else if (str.equals("고블린 (40%)")) {
                    adspinLOGInt = 40;
                }else if (str.equals("임프 (50%)")) {
                    adspinLOGInt = 50;
                }else if (str.equals("고급 오거 (90%)")) {
                    adspinLOGInt = 90;
                }else if (str.equals("고급 고블린 (120%)")) {
                    adspinLOGInt = 120;
                }else if (str.equals("고급 임프 (150%)")) {
                    adspinLOGInt = 150;
                }
            }

            public void onNothingSelected(AdapterView<?> paramAdapterView) {}

        });

        Spinner masterySpinner = (Spinner)findViewById(R.id.masterySpinner);
        adspinMastery = ArrayAdapter.createFromResource(context, R.array.masterySelected, R.layout.support_simple_spinner_dropdown_item);
        adspinMastery.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        masterySpinner.setAdapter(adspinMastery);
        masterySpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            public void onItemSelected(AdapterView<?> paramAdapterView, View paramView, int paramInt, long paramLong)
            {
                String str = (String) adspinMastery.getItem(paramInt);
                if (str.equals("연습랭크")){
                    adspinMasteryInt = 0;
                }else if (str.equals("F랭크")){
                    adspinMasteryInt = 1;
                }else if (str.equals("E랭크")){
                    adspinMasteryInt = 2;
                }else if (str.equals("D랭크")){
                    adspinMasteryInt = 3;
                }else if (str.equals("C랭크")){
                    adspinMasteryInt = 4;
                }else if (str.equals("B랭크")){
                    adspinMasteryInt = 5;
                }else if (str.equals("A랭크")){
                    adspinMasteryInt = 6;
                }else if (str.equals("9랭크")){
                    adspinMasteryInt = 7;
                }else if (str.equals("8랭크")){
                    adspinMasteryInt = 8;
                }else if (str.equals("7랭크")){
                    adspinMasteryInt = 9;
                }else if (str.equals("6랭크")){
                    adspinMasteryInt = 10;
                }else if (str.equals("5랭크")){
                    adspinMasteryInt = 11;
                }else if (str.equals("4랭크")){
                    adspinMasteryInt = 12;
                }else if (str.equals("3랭크")){
                    adspinMasteryInt = 13;
                }else if (str.equals("2랭크")){
                    adspinMasteryInt = 14;
                }else if (str.equals("1랭크")){
                    adspinMasteryInt = 15;
                }
            }

            public void onNothingSelected(AdapterView<?> paramAdapterView) {}
        });

        Spinner grandMasterSpinner = (Spinner)findViewById(R.id.grandMasterSpinner);
        adspinGrandMaster = ArrayAdapter.createFromResource(context, R.array.grandMasterSelected, R.layout.support_simple_spinner_dropdown_item);
        adspinGrandMaster.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        grandMasterSpinner.setAdapter(adspinGrandMaster);
        grandMasterSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            // 4번째
            public void onItemSelected(AdapterView<?> paramAdapterView, View paramView, int paramInt, long paramLong)
            {
                adspinGrandMasterStr = (CharSequence) adspinGrandMaster.getItem(paramInt);
                AfterTradeValue();
            }

            public void onNothingSelected(AdapterView<?> paramAdapterView) {}
        });

        Button tradeMeans1 = (Button)findViewById(R.id.tradeMeans_1);
        tradeMeans1.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent1);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(1);
            }
        });
        Button tradeMeans2 = (Button)findViewById(R.id.tradeMeans_2);
        tradeMeans2.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent2);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(2);
            }
        });
        Button tradeMeans3 = (Button)findViewById(R.id.tradeMeans_3);
        tradeMeans3.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent3);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(3);
            }
        });
        Button tradeMeans4 = (Button)findViewById(R.id.tradeMeans_4);
        tradeMeans4.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent4);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(4);
            }
        });
        Button tradeMeans5 = (Button)findViewById(R.id.tradeMeans_5);
        tradeMeans5.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent5);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(5);
            }
        });
        Button tradeMeans6 = (Button)findViewById(R.id.tradeMeans_6);
        tradeMeans6.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent6);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(6);
            }
        });
        Button tradeMeans7 = (Button)findViewById(R.id.tradeMeans_7);
        tradeMeans7.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent7);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(7);
            }
        });
        Button tradeMeans8 = (Button)findViewById(R.id.tradeMeans_8);
        tradeMeans8.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent8);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(8);
            }
        });
        Button tradeMeans9 = (Button)findViewById(R.id.tradeMeans_9);
        tradeMeans9.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                TextView localTextView = (TextView) findViewById(R.id.rideContent9);
                instanceTradeMaxCount = Integer.valueOf((String)localTextView.getText());
                AfterTradeMeansClick(9);
            }
        });

        HorizontalScrollView finishScrollView = (HorizontalScrollView)findViewById(R.id.finishScrollView);
        EditText finishContent1_2 = (EditText)findViewById(R.id.finishContent1_2);
        finishContent1_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View paramView, int paramInt, KeyEvent paramKeyEvent)
            {
                // 14 번째
                if (!time1.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent1_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("티르코네일").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time1))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent1_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent1_5)).setText(time1 + "초");
                }
                return false;
            }
        });
        EditText finishContent2_2 = (EditText)findViewById(R.id.finishContent2_2);
        finishContent2_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View paramView, int paramInt, KeyEvent paramKeyEvent)
            {
                // 15 번째
                if (!time2.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent2_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("던바튼").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time2))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent2_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent2_5)).setText(time2 + "초");
                }
                return false;
            }
        });
        EditText finishContent3_2 = (EditText)findViewById(R.id.finishContent3_2);
        finishContent3_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 16 번째
                if (!time3.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent3_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("반호르").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time3))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent3_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent3_5)).setText(time3 + "초");
                }
                return false;
            }
        });
        EditText finishContent4_2 = (EditText)findViewById(R.id.finishContent4_2);
        finishContent4_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 17 번째
                if (!time4.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent4_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("이멘마하").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time4))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent4_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent4_5)).setText(time4 + "초");
                }
                return false;
            }
        });
        EditText finishContent5_2 = (EditText)findViewById(R.id.finishContent5_2);
        finishContent5_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 18 번째
                if (!time5.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent5_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("탈틴").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time5))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent5_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent5_5)).setText(time5 + "초");
                }
                return false;
            }
        });
        EditText finishContent6_2 = (EditText)findViewById(R.id.finishContent6_2);
        finishContent6_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 19 번째
                if (!time6.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent6_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("타라").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time6))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent6_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent6_5)).setText(time6 + "초");
                }
                return false;
            }
        });
        EditText finishContent7_2 = (EditText)findViewById(R.id.finishContent7_2);
        finishContent7_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 20 번째
                if (!time7.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent7_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("카브항구").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time7))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent7_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent7_5)).setText(time7 + "초");
                }
                return false;
            }
        });
        EditText finishContent8_2 = (EditText)findViewById(R.id.finishContent8_2);
        finishContent8_2.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View view, int index, KeyEvent keyEvent) {
                // 21 번째
                if (!time8.equals("0"))
                {
                    String str = String.valueOf(((EditText)findViewById(R.id.finishContent8_2)).getText());
                    if (str.equals("")) {
                        str = "0";
                    }
                    int i = Integer.valueOf(String.valueOf(str));
                    int j = (int)Math.floor((1.0D + LOGValue + masteryValue) * instanceTradeMaxCount * i);
                    rankArray.get("벨바스트").setFinishValue(String.valueOf(Math.round(j * 100 / Integer.valueOf(time8))));
                    tradeRanking();
                    ((TextView)findViewById(R.id.finishContent8_4)).setText(String.valueOf(j));
                    ((TextView)findViewById(R.id.finishContent8_5)).setText(time8 + "초");
                }
                return false;
            }
        });
        Button tradeResetButton = (Button)findViewById(R.id.tradeResetButton);
        tradeResetButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                EditText localEditText1 = (EditText)findViewById(R.id.finishContent1_2);
                EditText localEditText2 = (EditText)findViewById(R.id.finishContent2_2);
                EditText localEditText3 = (EditText)findViewById(R.id.finishContent3_2);
                EditText localEditText4 = (EditText)findViewById(R.id.finishContent4_2);
                EditText localEditText5 = (EditText)findViewById(R.id.finishContent5_2);
                EditText localEditText6 = (EditText)findViewById(R.id.finishContent6_2);
                EditText localEditText7 = (EditText)findViewById(R.id.finishContent7_2);
                EditText localEditText8 = (EditText)findViewById(R.id.finishContent8_2);
                localEditText1.setText("");
                localEditText2.setText("");
                localEditText3.setText("");
                localEditText4.setText("");
                localEditText5.setText("");
                localEditText6.setText("");
                localEditText7.setText("");
                localEditText8.setText("");
                TextView localTextView1 = (TextView)findViewById(R.id.finishContent1_3);
                TextView localTextView2 = (TextView)findViewById(R.id.finishContent2_3);
                TextView localTextView3 = (TextView)findViewById(R.id.finishContent3_3);
                TextView localTextView4 = (TextView)findViewById(R.id.finishContent4_3);
                TextView localTextView5 = (TextView)findViewById(R.id.finishContent5_3);
                TextView localTextView6 = (TextView)findViewById(R.id.finishContent6_3);
                TextView localTextView7 = (TextView)findViewById(R.id.finishContent7_3);
                TextView localTextView8 = (TextView)findViewById(R.id.finishContent8_3);
                localTextView1.setText("");
                localTextView2.setText("");
                localTextView3.setText("");
                localTextView4.setText("");
                localTextView5.setText("");
                localTextView6.setText("");
                localTextView7.setText("");
                localTextView8.setText("");
                TextView localTextView9 = (TextView)findViewById(R.id.finishContent1_4);
                TextView localTextView10 = (TextView)findViewById(R.id.finishContent2_4);
                TextView localTextView11 = (TextView)findViewById(R.id.finishContent3_4);
                TextView localTextView12 = (TextView)findViewById(R.id.finishContent4_4);
                TextView localTextView13 = (TextView)findViewById(R.id.finishContent5_4);
                TextView localTextView14 = (TextView)findViewById(R.id.finishContent6_4);
                TextView localTextView15 = (TextView)findViewById(R.id.finishContent7_4);
                TextView localTextView16 = (TextView)findViewById(R.id.finishContent8_4);
                localTextView9.setText("");
                localTextView10.setText("");
                localTextView11.setText("");
                localTextView12.setText("");
                localTextView13.setText("");
                localTextView14.setText("");
                localTextView15.setText("");
                localTextView16.setText("");
                TextView localTextView17 = (TextView)findViewById(R.id.finishContent1_5);
                TextView localTextView18 = (TextView)findViewById(R.id.finishContent2_5);
                TextView localTextView19 = (TextView)findViewById(R.id.finishContent3_5);
                TextView localTextView20 = (TextView)findViewById(R.id.finishContent4_5);
                TextView localTextView21 = (TextView)findViewById(R.id.finishContent5_5);
                TextView localTextView22 = (TextView)findViewById(R.id.finishContent6_5);
                TextView localTextView23 = (TextView)findViewById(R.id.finishContent7_5);
                TextView localTextView24 = (TextView)findViewById(R.id.finishContent8_5);
                localTextView17.setText("");
                localTextView18.setText("");
                localTextView19.setText("");
                localTextView20.setText("");
                localTextView21.setText("");
                localTextView22.setText("");
                localTextView23.setText("");
                localTextView24.setText("");
            }
        });
    }
    
    public void AfterTradeTown() {
        Spinner spinner = (Spinner)findViewById(R.id.itemSpinner);
        spinner.setPrompt("교역 아이템을 선택하시오.");
        showAllTown();
        if(adspinStr.equals("티르코네일")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected1, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent1_2);
            tempText1.setEnabled(false);
            isView1 = false;
        } else if(adspinStr.equals("던바튼")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected2, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent2_2);
            tempText1.setEnabled(false);
            isView2 = false;
        } else if(adspinStr.equals("반호르")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected3, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent3_2);
            tempText1.setEnabled(false);
            isView3 = false;
        } else if(adspinStr.equals("이멘마하")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected4, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent4_2);
            tempText1.setEnabled(false);
            isView4 = false;
        } else if(adspinStr.equals("탈틴")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected5, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent5_2);
            tempText1.setEnabled(false);
            isView5 = false;
        } else if(adspinStr.equals("타라")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected6, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent6_2);
            tempText1.setEnabled(false);
            isView6 = false;
        } else if(adspinStr.equals("카브항구")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected7, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent7_2);
            tempText1.setEnabled(false);
            isView7 = false;
        } else if(adspinStr.equals("벨바스트")) {
            adspinItem = ArrayAdapter.createFromResource(context, R.array.townItemSelected8, R.layout.support_simple_spinner_dropdown_item);
            EditText tempText1 = (EditText)findViewById(R.id.finishContent8_2);
            tempText1.setEnabled(false);
            isView8 = false;
        }
        adspinItem.setDropDownViewResource(R.layout.support_simple_spinner_dropdown_item);
        spinner.setAdapter(adspinItem);
        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                adspinItemStr = adspinItem.getItem(position);
                AfterTradeTownItem();
            }
            
            public void onNothingSelected(AdapterView<?> parent) {
            }
        });
    }
    
    public void AfterTradeTownItem() {
        String sql = "SELECT weight, slotValue FROM TRADEITEM WHERE town = \'" + adspinStr + "\' AND item = \'" + adspinItemStr + "\'";
        Cursor cursor = tradeDb.rawQuery(sql, null);

        String weight = "";
        String slotValue = "";

        while(cursor.moveToNext()) {
            weight = cursor.getString(0);
            slotValue = cursor.getString(1);
        }
        TextView countNumber = (TextView)findViewById(R.id.countNumber);
        countNumber.setText("개당 무게 : " + weight + " || 슬롯당 최대 수량 : " + slotValue);
        instanceItemCount = Integer.valueOf(weight);
        instanceMaxCount = Integer.valueOf(slotValue);
        AfterTradeValue();
    }
    
    public void AfterTradeValue() {
        if(instanceMaxCount == 0) {
            return;
        }
        if(instanceItemCount != 0) {
            if(!adspinGrandMasterStr.equals("")) {
                int grandMasterValue = 0;
                if(adspinGrandMasterStr.equals("사용안함")) {
                    grandMasterValue = 0;
                } else {
                    grandMasterValue = 1;
                }

                // ***** 최대 수량 시작 *****
                // 마차                    -   슬롯 8 / 무게 900
                TextView rideContent1 = (TextView) findViewById(R.id.rideContent1);
                rideContent1.setText(String.valueOf((int) Math.min((( 8 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 900 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 마차(교역파트너)        -   슬롯 9 / 무게 1000
                TextView rideContent2 = (TextView) findViewById(R.id.rideContent2);
                rideContent2.setText(String.valueOf((int) Math.min((( 9 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1000 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 마차(윌리엄)            -   슬롯 9 / 무게 1100
                TextView rideContent3 = (TextView) findViewById(R.id.rideContent3);
                rideContent3.setText(String.valueOf((int) Math.min((( 9 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1100 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 마차(알파카)            -   슬롯 10 / 무게 1100
                TextView rideContent4 = (TextView) findViewById(R.id.rideContent4);
                rideContent4.setText(String.valueOf((int) Math.min((( 10 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1100 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 코끼리                  -   슬롯 7 / 무게 1700
                TextView rideContent5 = (TextView) findViewById(R.id.rideContent5);
                rideContent5.setText(String.valueOf((int) Math.min((( 7 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1700 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 코끼리(교역파트너)      -   슬롯 8 / 무게 1800
                TextView rideContent6 = (TextView) findViewById(R.id.rideContent6);
                rideContent6.setText(String.valueOf((int) Math.min((( 8 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1800 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // 코끼리(윌리엄)          -   슬롯 8 / 무게 1900
                TextView rideContent7 = (TextView) findViewById(R.id.rideContent7);
                rideContent7.setText(String.valueOf((int) Math.min((( 8 + grandMasterValue ) * instanceMaxCount), Math.floor( ( 1900 + ( grandMasterValue * 100 ) ) / instanceItemCount ))));

                // ***** 최대 수량 끝 *****
            }
        }
    }
    
    public void AfterTradeMeansClick(int tradeMeansValue) {
        String time = "";
        String sql = "";
        HorizontalScrollView finishScrollView = (HorizontalScrollView)findViewById(R.id.finishScrollView);
        finishScrollView.requestFocus();
        TextView tradeMeansSelected = (TextView)findViewById(R.id.tradeMeansSelected);
        if((tradeMeansValue == 1) || (tradeMeansValue == 2) || (tradeMeansValue == 3) || (tradeMeansValue == 4)) {
            sql = "SELECT endTown, time FROM TRADECONTENT WHERE startTown = \'" + adspinStr + "\' AND tradeMeans = \'마차\'";
        } else if((tradeMeansValue == 5) || (tradeMeansValue == 6) || (tradeMeansValue == 7)) {
            sql = "SELECT endTown, time FROM TRADECONTENT WHERE startTown = \'" + adspinStr + "\' AND tradeMeans = \'코끼리\'";
        } else if(tradeMeansValue == 8) {
            sql = "SELECT endTown, time FROM TRADECONTENT WHERE startTown = \'" + adspinStr + "\' AND tradeMeans = \'등짐\'";
        } else if(tradeMeansValue == 9) {
            sql = "SELECT endTown, time FROM TRADECONTENT WHERE startTown = \'" + adspinStr + "\' AND tradeMeans = \'손수레\'";
        }
        if(tradeMeansValue == 1) {
            tradeMeansSelected.setText("운송수단 : 마차");
        } else if(tradeMeansValue == 2) {
            tradeMeansSelected.setText("운송수단 : 마차(교역파트너)");
        } else if(tradeMeansValue == 3) {
            tradeMeansSelected.setText("운송수단 : 마차(윌리엄)");
        } else if(tradeMeansValue == 4) {
            tradeMeansSelected.setText("운송수단 : 마차(알파카)");
        } else if(tradeMeansValue == 5) {
            tradeMeansSelected.setText("운송수단 : 코끼리");
        } else if(tradeMeansValue == 6) {
            tradeMeansSelected.setText("운송수단 : 코끼리(교역파트너)");
        } else if(tradeMeansValue == 7) {
            tradeMeansSelected.setText("운송수단 : 코끼리(윌리엄)");
        } else if(tradeMeansValue == 8) {
            tradeMeansSelected.setText("운송수단 : 등짐");
        } else if(tradeMeansValue == 9) {
            tradeMeansSelected.setText("운송수단 : 손수레");
        }
        Cursor cursor = tradeDb.rawQuery(sql, null);
        if(adspinLOGInt != 0) {
            LOGValue = ((double)adspinLOGInt / 100.0);
        }
        if(adspinMasteryInt != 0) {
            masteryValue = ((double)adspinMasteryInt / 100.0);
        }
        time1 = "0";
        time2 = "0";
        time3 = "0";
        time4 = "0";
        time5 = "0";
        time6 = "0";
        time7 = "0";
        time8 = "0";
        while(cursor.moveToNext()) {
            time = cursor.getString(1);
            if(cursor.getString(0).equals("티르코네일")) {
                time1 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent1_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("티르코네일").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent1_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent1_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("던바튼")) {
                time2 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent2_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("던바튼").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent2_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent2_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("반호르")) {
                time3 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent3_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("반호르").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent3_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent3_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("이멘마하")) {
                time4 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent4_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("이멘마하").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent4_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent4_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("탈틴")) {
                time5 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent5_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("탈틴").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent5_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent5_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("타라")) {
                time6 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent6_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("타라").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent6_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent6_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("카브항구")) {
                time7 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent7_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("타라").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent7_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent7_5);
                tempText5.setText(time + "초");
            } else if(cursor.getString(0).equals("벨바스트")) {
                time8 = time;
                EditText tempText1 = (EditText)findViewById(R.id.finishContent8_2);
                String tempTextOfText = String.valueOf(tempText1.getText());
                if(tempTextOfText.equals("")) {
                    tempTextOfText = "0";
                }
                int tempThan = Integer.valueOf(String.valueOf(tempTextOfText));
                int addValue = (int)Math.floor(((((1.0 + LOGValue) + masteryValue) * (double)instanceTradeMaxCount) * (double)tempThan));
                rankArray.get("벨바스트").setFinishValue(String.valueOf(Math.round((float)((addValue * 100) / Integer.valueOf(time)))));

                TextView tempText4 = (TextView)findViewById(R.id.finishContent8_4);
                tempText4.setText(String.valueOf(addValue));

                TextView tempText5 = (TextView)findViewById(R.id.finishContent8_5);
                tempText5.setText(time + "초");
            }
        }
        tradeRanking();
    }
    
    public void showAllTown() {
        if(!isView1) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent1_2);
            tempText1.setEnabled(true);
            isView1 = true;
            return;
        }
        if(!isView2) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent2_2);
            tempText1.setEnabled(true);
            isView2 = true;
            return;
        }
        if(!isView3) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent3_2);
            tempText1.setEnabled(true);
            isView3 = true;
            return;
        }
        if(!isView4) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent4_2);
            tempText1.setEnabled(true);
            isView4 = true;
            return;
        }
        if(!isView5) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent5_2);
            tempText1.setEnabled(true);
            isView5 = true;
            return;
        }
        if(!isView6) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent6_2);
            tempText1.setEnabled(true);
            isView6 = true;
            return;
        }
        if(!isView7) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent7_2);
            tempText1.setEnabled(true);
            isView7 = true;
            return;
        }
        if(!isView8) {
            EditText tempText1 = (EditText)findViewById(R.id.finishContent8_2);
            tempText1.setEnabled(true);
            isView8 = true;
        }
    }
    
    public void tradeRanking() {
        int[] score = new int[8];
        int[] rank = new int[8];
        if(rankArray.get("티르코네일").getFinishValue().equals("")) {
            score[0] = 0;
        } else {
            score[0] = Integer.valueOf(rankArray.get("티르코네일").getFinishValue());
        }
        if(rankArray.get("던바튼").getFinishValue().equals("")) {
            score[1] = 0;
        } else {
            score[1] = Integer.valueOf(rankArray.get("던바튼").getFinishValue());
        }
        if(rankArray.get("반호르").getFinishValue().equals("")) {
            score[2] = 0;
        } else {
            score[2] = Integer.valueOf(rankArray.get("반호르").getFinishValue());
        }
        if(rankArray.get("반호르").getFinishValue().equals("")) {
            score[3] = 0;
        } else {
            score[3] = Integer.valueOf(rankArray.get("이멘마하").getFinishValue());
        }
        if(rankArray.get("탈틴").getFinishValue().equals("")) {
            score[4] = 0;
        } else {
            score[4] = Integer.valueOf(rankArray.get("탈틴").getFinishValue());
        }
        if(rankArray.get("타라").getFinishValue().equals("")) {
            score[5] = 0;
        } else {
            score[5] = Integer.valueOf(rankArray.get("타라").getFinishValue());
        }
        if(rankArray.get("카브항구").getFinishValue().equals("")) {
            score[6] = 0;
        } else {
            score[6] = Integer.valueOf(rankArray.get("카브항구").getFinishValue());
        }
        if(rankArray.get("벨바스트").getFinishValue().equals("")) {
            score[7] = 0;
        } else {
            score[7] = Integer.valueOf(rankArray.get("벨바스트").getFinishValue());
        }
        for(int i = 0; i < 8; i++) {
            for(int j = 0; j < 8; j++) {
                if(score[i] < score[j]) {
                    rank[i] = (rank[i] + 1);
                }
            }
        }

        if(isView1) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent1_3);
            tempText1.setText((rank[0] + 1) + "위 (" + score[0] + ")");
        }
        if(isView2) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent2_3);
            tempText1.setText((rank[1] + 1) + "위 (" + score[1] + ")");
        }
        if(isView3) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent3_3);
            tempText1.setText((rank[2] + 1) + "위 (" + score[2] + ")");
        }
        if(isView4) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent4_3);
            tempText1.setText((rank[3] + 1) + "위 (" + score[3] + ")");
        }
        if(isView5) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent5_3);
            tempText1.setText((rank[4] + 1) + "위 (" + score[4] + ")");
        }
        if(isView6) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent6_3);
            tempText1.setText((rank[5] + 1) + "위 (" + score[5] + ")");
        }
        if(isView7) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent7_3);
            tempText1.setText((rank[6] + 1) + "위 (" + score[6] + ")");
        }
        if(isView8) {
            TextView tempText1 = (TextView)findViewById(R.id.finishContent8_3);
            tempText1.setText((rank[7] + 1) + "위 (" + score[7] + ")");
        }
    }
}
