/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication;

import android.support.v7.app.AppCompatActivity;
import android.widget.TextView;
import android.os.Bundle;
import android.view.View;
import android.content.Intent;
import java.io.Serializable;
import com.addon.user.myapplication.view.NoticeItem;

public class DetailActivity extends AppCompatActivity {
    private TextView noticeContentView;
    private TextView noticeDateView;
    private TextView noticeTitleView;
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.notice_item);
        noticeTitleView = (TextView)findViewById(R.id.noticeTitleView);
        noticeContentView = (TextView)findViewById(R.id.noticeContentView);
        noticeDateView = (TextView)findViewById(R.id.noticeDateView);
        Intent intent = getIntent();
        NoticeItem noticeItem = (NoticeItem)intent.getSerializableExtra("noticeItem");
        noticeTitleView.setText(noticeItem.getTitle());
        noticeContentView.setText(noticeItem.getContent());
        noticeDateView.setText(noticeItem.getDate());
    }
}
