/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication;

import android.app.Application;

public class GlobalVariablesActivity extends Application {
    private String deviceID;
    private String deviceVersion;
    private String macAddress;
    
    public GlobalVariablesActivity() {
        deviceID = "";
        macAddress = "";
        deviceVersion = "";
    }
    
    public String getDeviceID() {
        return this.deviceID;
    }
    
    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }
    
    public String getMacAddress() {
        return this.macAddress;
    }
    
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }
    
    public String getDeviceVersion() {
        return this.deviceVersion;
    }
    
    public void setDeviceVersion(String deviceVersion) {
        this.deviceVersion = deviceVersion;
    }
}
