/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication;

import android.support.v4.view.GravityCompat;
import android.support.v7.app.AppCompatActivity;
import android.support.design.widget.NavigationView;
import android.view.Gravity;
import android.widget.Toast;
import android.database.sqlite.SQLiteDatabase;
import android.view.View;
import java.util.ArrayList;
import com.addon.user.myapplication.view.NoticeItem;
import android.content.Intent;
import android.support.v4.widget.DrawerLayout;
import android.os.Bundle;
import android.content.Context;
import android.util.DisplayMetrics;
import android.support.v7.widget.Toolbar;
import android.support.v7.app.ActionBarDrawerToggle;
import android.widget.ScrollView;
import com.addon.user.myapplication.layout.NoticeLayout;
import android.view.Menu;
import android.view.MenuItem;
import com.addon.user.myapplication.layout.TitleLayout;
import com.addon.user.myapplication.layout.TradeLayout;

public class MainActivity extends AppCompatActivity implements NavigationView.OnNavigationItemSelectedListener {
    private long backKeyPressedTime;
    DBHelper dbHelper;
    public int deviceHeight;
    public int deviceWidth;
    public static MainActivity thisActivity;
    private Toast toast;
    SQLiteDatabase tradeDb;
    
    public MainActivity() {
        backKeyPressedTime = 0;
        deviceWidth = 0;
        deviceHeight = 0;
    }
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        thisActivity = this;

        dbHelper = new DBHelper(getApplicationContext(), "tradeItem.db", null, 1);
        tradeDb = dbHelper.getWritableDatabase();

        DisplayMetrics displayMetrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
        deviceWidth = displayMetrics.widthPixels;
        deviceHeight = displayMetrics.heightPixels;
        Toolbar toolbar = (Toolbar)findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        DrawerLayout drawer = (DrawerLayout)findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.addDrawerListener(toggle);
        toggle.syncState();

        NavigationView navigationView = (NavigationView)findViewById(R.id.nav_view);
        navigationView.setItemIconTintList(null);
        navigationView.setNavigationItemSelectedListener(this);
        ScrollView contentView = (ScrollView)findViewById(R.id.contentScrollView);
        if(contentView != null) {
            contentView.removeAllViews();
        }
        NoticeLayout noticeLayout = new NoticeLayout(this);
        contentView.addView(noticeLayout);
        noticeLayout.initialization(null);
        noticeLayout.setData(null);
    }
    
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        if(drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(Gravity.START);
            return;
        }
        if(System.currentTimeMillis() > (backKeyPressedTime + 2000)) {
            backKeyPressedTime = System.currentTimeMillis();
            showGuide();
            return;
        }
        if(System.currentTimeMillis() <= (backKeyPressedTime + 2000)) {
            finish();
            toast.cancel();
        }
    }
    
    public void showGuide() {
        toast = Toast.makeText(this, "앱 종료를 하시려면 '뒤로 가기'를 한번 더 눌러주십시오.", Toast.LENGTH_SHORT);
        toast.show();
    }
    
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }
    
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        if(id == R.id.action_settings) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
    
    public boolean onNavigationItemSelected(MenuItem item) {
        int id = item.getItemId();
        ScrollView contentView = (ScrollView) findViewById(R.id.contentScrollView);
        if(id == R.id.nav_notice) {
            if(contentView != null) {
                contentView.removeAllViews();
            }
            NoticeLayout noticeLayout = new NoticeLayout(this);
            contentView.addView(noticeLayout);
            noticeLayout.initialization(null);
            noticeLayout.setData(null);
        } else if(id == R.id.nav_title) {
            if (contentView != null) {
                contentView.removeAllViews();
            }
            TitleLayout titleLayout = new TitleLayout(this);
            contentView.addView(titleLayout);
            titleLayout.setData(tradeDb, null);
            titleLayout.initialization(null);
        }else if(id == R.id.nav_trade) {
            if(contentView != null) {
                contentView.removeAllViews();
            }
            TradeLayout tradeLayout = new TradeLayout(this);
            contentView.addView(tradeLayout);
            tradeLayout.initialization(null);
            tradeLayout.setData(tradeDb, null);
            tradeLayout.tradeLayoutAdd();
        }
        DrawerLayout drawer = (DrawerLayout)findViewById(R.id.drawer_layout);
        drawer.closeDrawer(Gravity.START);
        return true;
    }
    
    public void noticeDetail(int position, View view, ArrayList arrayList) {
        NoticeItem noticeItem = (NoticeItem)arrayList.get(position);
        Intent intent = new Intent(this, DetailActivity.class);
        intent.putExtra("noticeItem", noticeItem);
        startActivity(intent);
    }
}
