/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.addon.user.myapplication;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import com.bumptech.glide.request.target.GlideDrawableImageViewTarget;
import com.bumptech.glide.Glide;
import com.bumptech.glide.RequestManager;
import com.bumptech.glide.DrawableTypeRequest;
import com.bumptech.glide.request.target.Target;
import android.content.Intent;

public class StartActivity extends AppCompatActivity {
    
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_start);
        ImageView backgroundImage = (ImageView)findViewById(R.id.gifImage);
        GlideDrawableImageViewTarget gifImage = new GlideDrawableImageViewTarget(backgroundImage);
        Glide.with(this).load(Integer.valueOf(R.drawable.background_start_v2)).into(gifImage);
        backgroundImage.setOnClickListener(new View.OnClickListener() {
            public void onClick(View view) {
                startMainActivity();
            }
        });
    }
    
    public void startMainActivity() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
        finish();
    }
}
